// Generated by CoffeeScript 1.3.3
(function() {
  var UIWebViewDetect;

  UIWebViewDetect = (function() {

    UIWebViewDetect.prototype.regex = /(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/i;

    function UIWebViewDetect() {
      if (this.isUIWebView()) {
        $('html').addClass('uiwebview');
      }
    }

    UIWebViewDetect.prototype.isUIWebView = function() {
      return this.regex.test(navigator.userAgent);
    };

    return UIWebViewDetect;

  })();

  window.UIWebViewDetector = new UIWebViewDetect();

  $.isUIWebView = function() {
    return UIWebViewDetector.isUIWebView();
  };

}).call(this);
